//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickTabs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class QuickTabs : global::System.Configuration.ApplicationSettingsBase {
        
        private static QuickTabs defaultInstance = ((QuickTabs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QuickTabs())));
        
        public static QuickTabs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewFretCounter {
            get {
                return ((bool)(this["ViewFretCounter"]));
            }
            set {
                this["ViewFretCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewNavDots {
            get {
                return ((bool)(this["ViewNavDots"]));
            }
            set {
                this["ViewNavDots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewCompactCtxMenu {
            get {
                return ((bool)(this["ViewCompactCtxMenu"]));
            }
            set {
                this["ViewCompactCtxMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewLargeFretboard {
            get {
                return ((bool)(this["ViewLargeFretboard"]));
            }
            set {
                this["ViewLargeFretboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewDarkMode {
            get {
                return ((bool)(this["ViewDarkMode"]));
            }
            set {
                this["ViewDarkMode"] = value;
            }
        }
    }
}
